### ISSUE TITLE
User session is lost when Chrome is closed (on Android)

### ISSUE THREAD

**Issue by gmcabrita** [freshreader/core#68] opened 2020-05-18 20:34 UTC
Short video showing the issue: https://streamable.com/x6crpa

**Comment by maximevaillancourt** [comment] 2020-05-18 23:00
Hi Gonçalo, thanks for taking the time to submit this. 🙌 

This behavior is intentional for privacy purposes, though I'm open to changing it if there's enough demand for it.

Here's the rationale: expiring sessions when the browser closes reduces the risk of someone logging into their Freshreader account and forgetting to logout when they're done. Because there is no password on Freshreader accounts, if a malicious person gets ahold of someone's Freshreader account number, they can effectively take full control of the account (view their reading list, save content to it, and delete the account). By expiring user sessions when the browser is closed, this situation becomes less likely to happen.

I only intend to implement this behavior in the Web version. When using the Freshreader native app for Android (which currently exists but doesn't let you see your list of saved content [yet](https://github.com/freshreader/android/issues/2)), I'll make it so that you won't have to log in every time, as I assume that mobile devices are typically personal devices, so the above risk is less present.

Let me know what you think!

**Comment by gmcabrita** [comment] 2020-05-19 09:12
This makes sense, just seemed weird that the session expired on my phone's browser but not on the desktop.

**Comment by gmcabrita** [comment] 2020-05-19 12:17
> What browser do you use?

I'm on Chrome (under Linux).

**Comment by maximevaillancourt** [comment] 2020-05-20 00:28
I can't seem to reproduce this (same Chrome version, though on Windows 10, even with the "Continue running background apps when Google Chrome is closed" option enabled).

I'll close this since the behavior is intentional anyway. Thanks again for taking the time to report this!

**Closed by maximevaillancourt** 2020-05-20 00:28 UTC
